### ISSUE TITLE
Android Issues

### ISSUE THREAD

**Issue by bbedward** [rotilho/jnano-commons#3]
Hi,

I recently switched Natrium to use JNano classes and functions, for code simplification and because I planned on using JNano anyway for Mnemonics down the line.

I ran into a couple issues, the first one may not be an issue with library but an issue with my build settings (I haven't been able to figure it out yet though)

On a android 6.0, 32-bit device (armeabi-v7a) - I get the following when trying `NanoKeys.createPrivateKey`

```11-29 10:35:47.750 6190-6190/co.banano.natriumwallet E/AndroidRuntime: FATAL EXCEPTION: main
    Process: co.banano.natriumwallet, PID: 6190
    java.lang.NoClassDefFoundError: com.rotilho.jnano.commons.-$$Lambda$NanoKeys$To3fvqZ6OqDSbslOGNAscJLDYzE
        at com.rotilho.jnano.commons.NanoKeys.createPrivateKey(NanoKeys.java:12)
        at co.banano.natriumwallet.KaliumUtil.seedToPrivate(KaliumUtil.java:48)
        at co.banano.natriumwallet.model.Credentials.setSeed(Credentials.java:55)
        at co.banano.natriumwallet.ui.intro.IntroWelcomeFragment$ClickHandlers.lambda$onClickNewWallet$0(IntroWelcomeFragment.java:74)
        at co.banano.natriumwallet.ui.intro.-$$Lambda$IntroWelcomeFragment$ClickHandlers$J_jelFXY-c9L5iUyzoeIh90MgC4.execute(lambda)
        at io.realm.Realm.executeTransaction(Realm.java:1431)
        at co.banano.natriumwallet.ui.intro.IntroWelcomeFragment$ClickHandlers.onClickNewWallet(IntroWelcomeFragment.java:72)
        at co.banano.natriumwallet.databinding.FragmentIntroWelcomeBindingImpl$OnClickListenerImpl1.onClick(FragmentIntroWelcomeBindingImpl.java:147)
        at android.view.View.performClick(View.java:5198)
        at android.view.View$PerformClick.run(View.java:21147)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Separate, but also occurring on older android versions is an issue with `NanoSeeds.generateSeed()`

I get the exception:

```
java.lang.NoSuchMethodError: No static method getInstanceStrong()Ljava/security/SecureRandom; in class Ljava/security/SecureRandom; or its super classes (declaration of 'java.security.SecureRandom' appears in /system/framework/core-libart.jar)
        at com.rotilho.jnano.commons.NanoSeeds.generateSeed(NanoSeeds.java:25)
        at co.banano.natriumwallet.KaliumUtil.generateSeed(KaliumUtil.java:29)
        at co.banano.natriumwallet.ui.intro.IntroWelcomeFragment$ClickHandlers.lambda$onClickNewWallet$0(IntroWelcomeFragment.java:74)
        at co.banano.natriumwallet.ui.intro.-$$Lambda$IntroWelcomeFragment$ClickHandlers$J_jelFXY-c9L5iUyzoeIh90MgC4.execute(lambda)
        at io.realm.Realm.executeTransaction(Realm.java:1431)
        at co.banano.natriumwallet.ui.intro.IntroWelcomeFragment$ClickHandlers.onClickNewWallet(IntroWelcomeFragment.java:72)
        at co.banano.natriumwallet.databinding.FragmentIntroWelcomeBindingImpl$OnClickListenerImpl1.onClick(FragmentIntroWelcomeBindingImpl.java:147)
        at android.view.View.performClick(View.java:5198)
        at android.view.View$PerformClick.run(View.java:21147)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

This is something I could account for myself if you do not want to, but appears older Android SDKs do not support `SecureRandom.getInstanceStrong()` , which is likely why NWC went with a custom implementation as seen here: https://github.com/bbedward/natrium-nano-wallet/blob/master/app/src/main/java/co/banano/natriumwallet/util/LinuxSecureRandom.java

I'd appreciate any help on these problems, of course Natrium full source can be seen at https://github.com/bbedward/natrium-nano-wallet

On 64-bit, newer devices everything that I have used has worked with no problems.

Thanks!

**Comment by bbedward** [comment]
Looking further I suspect I see why

```
 requireNonNull(byteArrays, "Byte Arrays can't be null");
```

Requires min API 19 on android (my min is 17, but should still be fine for my 6.0 marshmallow test)

However,

```
Stream.of
```

requires Android API 24, Android 7.0+. Seems Java 8 streams requires 7.0 

This may work for me, will try it and get back:

https://github.com/stefan-zobel/streamsupport

**Comment by rotilho** [comment]
Hello bbedward, those are easy to fix and definitely it would be nice to keep the compatibility with old devices.

If this stream support lib don't work and you feel like submit a PR let me know, if not I'll try to work on that this night or in the worse case Monday.

Not sure if possible, but afterwards I'll try to find a way to set up an Android environment to avoid this kind of situation in the future.

**Comment by bbedward** [comment]
Seems like it does not work out of the box, I'll create a pull that removes usage of java 8 streams if that's ok with you.

**Comment by rotilho** [comment]
About security random it seems it was added in API 26.

https://developer.android.com/reference/java/security/SecureRandom#getInstanceStrong()

The [recommendation ](https://android-developers.googleblog.com/2016/06/security-crypto-provider-deprecated-in.html) is to not specify the provider and since[ API 4.2 they are using OpenSSL](https://android-developers.googleblog.com/2013/02/using-cryptography-to-store-credentials.html) as default so new SecurityRandom() is safe and the same applies to JDK which use urandom under the hood.

What's the minimal version you are using?

**Comment by bbedward** [comment]
I encountered the issue on API 23, the minimum for natrium is KitKat (API 17/4.4). Would like to keep it 4.4+ since a lot of Venezuelans and other countries still have people using these older devices.

**Comment by rotilho** [comment]
New version released with your PR

The NanoSeed issue was also adressed

**Comment by bbedward** [comment]
Thank you for your work on this, much appreciated

**Comment by rotilho** [comment]
It was basically your work :)

Thank you
